spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/docker_mybatis_snowflake?useSSL=false&useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 20 # 连接池最大连接数，默认是10
      minimumIdle: 5  # 最小空闲连接数量
      idleTimeout: 600000 # 空闲连接存活最大时间，默认600000（10分钟）
      connectionTimeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      maxLifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
      shutdown-timeout: 100 # 关闭超时时间
    timeout: 60s


