spring:
  application:
    name: spring-boot-mybatis-snowflake
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true # 处理404
  web:
    resources:
      add-mappings: false # 关闭资源映射
server:
  port: 9002
  servlet:
    context-path: /mybatis

# sql
mybatis-plus:
  configuration:
    # 指定日志实现
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #开启下划线转驼峰
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml
  level:
    cn.z201.example.snowflake.dao: debug
