spring:
  application:
    name: spring-boot-aop
  mvc:
    throw-exception-if-no-handler-found: true # 处理404
  web:
    resources:
      add-mappings: false # 关闭资源映射
server:
  port: 9003
  servlet:
    context-path: /aop

logging:
  config: classpath:logback.xml

