spring:
  datasource:
    url: jdbc:mysql://mysql:3306/docker_mybatis_audit?useSSL=false&useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 20 # 连接池最大连接数，默认是10
      minimumIdle: 5  # 最小空闲连接数量
      idleTimeout: 600000 # 空闲连接存活最大时间，默认600000（10分钟）
      connectionTimeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      maxLifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-test-query: SELECT 1

logging:
  level:
    cn:
      z201:
        audit:
          persistence:
            dao: debug
    org:
      springframework: info