spring:
  application:
    name: spring-test-delayed
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true # 处理404
  web:
    resources:
      add-mappings: false # 关闭资源映射
  webflux:
    base-path: /delayed
server:
  port: 9016

logging:
  config: classpath:logback.xml