version : '3'

networks:
  network-redis-bloom:
    driver: bridge

services:
  web:
    container_name: cn.z201.docker-redis-bloom
    build:
      context: .
      dockerfile: docker-config/app/
    image: cn.z201.docker-redis-bloom
    networks:
      - network-redis-bloom
    expose:
      - '9008'
    ports:
      - '9008:9008'
    depends_on: # 等待其它服务启动完成
      - redis
    links:
      - redis
    healthcheck:
      test: "/bin/netstat -anpt|grep 9001"
      interval: 30s
      timeout: 3s
      retries: 1
