version : '3'
networks:
  network-docker-mybatis-explain:
    driver: bridge

services:
  web:
    container_name: cn.z201.docker-mybatis-explain
    build:
      context: .
      dockerfile: .
    image: cn.z201.docker-mybatis-explain
    networks:
      - network-docker-mybatis-explain
    expose:
      - '9023'
    ports:
      - '9023:9023'
    depends_on: # 等待其它服务启动完成
      - mysql
    links:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: "/bin/netstat -anpt|grep 9023"
      interval: 30s
      timeout: 3s
      retries: 1
  mysql:
    image: mysql:8.0
    container_name: mysql8.0-mybatis-explain
    networks:
      - network-docker-mybatis-explain
    expose:
      - '3306'
    ports:
      - '3311:3306'
    volumes:
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
      - ./docker-config/mysql/init:/docker-entrypoint-initdb.d # 初始化数据库
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--lower_case_table_names=1',
      '--default-time-zone=+8:00',
      '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=root # 设置root密码
    healthcheck:
      test: "/bin/netstat -anpt|grep 3306"
      interval: 30s
      timeout: 3s
      retries: 1

