version: '3'

services:
  redis-master:
    image: redis:5.0.6
    container_name: redis5.0.6-master
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
      - ./data/master:/data
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-slave1:
    image: redis:5.0.6
    container_name: redis5.0.6-slave1
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis5.0.6-master 6379
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
      - ./data/slave1:/data
    ports:
      - "6380:6379"
    networks:
      - redis-net
    depends_on:
      - redis-master

  redis-slave2:
    image: redis:5.0.6
    container_name: redis5.0.6-slave2
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis5.0.6-master 6379
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
      - ./data/slave2:/data
    ports:
      - "6381:6379"
    networks:
      - redis-net
    depends_on:
      - redis-master

networks:
  redis-net:
    driver: bridge