version : '3.5'
networks:
  network-docker-mybatis-snowflake:
    driver: bridge

services:
  web:
    container_name: cn.z201.docker-mybatis-snowflake
    build:
      context: .
      dockerfile: .
    image: cn.z201.docker-mybatis-snowflake
    networks:
      - network-docker-mybatis-snowflake
    expose:
      - '9002'
    ports:
      - '9002:9002'
    depends_on: # 等待其它服务启动完成
      - mysql
    links:
      - mysql
    healthcheck:
      test: "/bin/netstat -anpt|grep 9002"
      interval: 30s
      timeout: 3s
      retries: 1
  mysql:
    image: mysql:8.0
    container_name: mysql8.0-mybatis-snowflake
    networks:
      - network-docker-mybatis-snowflake
    expose:
      - '3306'
    ports:
      - '3309:3306'
    volumes:
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
      - ./docker-config/mysql/init:/docker-entrypoint-initdb.d # 初始化数据库
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--lower_case_table_names=1',
      '--default-time-zone=+8:00',
      '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=root # 设置root密码
    healthcheck:
      test: "/bin/netstat -anpt|grep 3306"
      interval: 30s
      timeout: 3s
      retries: 1

