spring:
  application:
    name: spring-webclient
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true # 处理404
  web:
    resources:
      add-mappings: false # 关闭资源映射
  webflux:
    base-path: /webclient
server:
  port: 9015

logging:
  config: classpath:logback.xml