zookeeper:
  curator:
    retryCount: 3 #重试次数
    elapsedTimeMs: 1000 #重试间隔时间
    sessionTimeoutMs: 1000 # session超时时间
    connectionTimeoutMs: 5000 # 连接超时时间
    connectString: 127.0.0.1:2181 # zookeeper 地址
