spring:
  application:
    name: distributed-lock-mysql
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true # 处理404
  web:
    resources:
      add-mappings: false # 关闭资源映射
server:
  port: 9004
  servlet:
    context-path: /lock

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.jdbc.core : DEBUG