spring:
  application:
    name: spring-boot-mysql-redis
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true # 处理404
  web:
    resources:
      add-mappings: false # 关闭资源映射
server:
  port: 0
  servlet:
    context-path: /redis

logging:
  config: classpath:logback-spring.xml

