# 这个配置文件没什么用
jdbc-driver: 'com.mysql.jdbc.Driver'
url: 'jdbc:mysql://localhost:3306/jelly?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8'

# mybatis xml 里面 & 需要转义成 &amp;
#url: 'jdbc:mysql://localhost:3306/jelly?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8'
