version: '3'

networks:
  network-distributed-lock-zookeeper:
    driver: bridge

services:
  zookeeper:
    image: zookeeper:3.7.1
    container_name: zookeeper3.7.1-distributed-lock
    networks:
      - network-distributed-lock-zookeeper
    expose:
      - '2181'
    ports:
      - '2181:2181'
    volumes:
      - ./docker-config/zookeeper/zoo.cfg:/conf/zoo.cfg
      - ./docker-config/zookeeper/jaas.conf:/conf/jaas.conf
      - ./docker-config/zookeeper/data:/data
      - ./docker-config/zookeeper/datalog:/datalog
    environment:
      - ZOO_MY_ID=1
      - JVMFLAGS=-Djava.security.auth.login.config=/conf/jaas.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: "/bin/netstat -anpt|grep 2181"
      interval: 30s
      timeout: 3s
      retries: 1