spring:
  mail:
    host: smtp.qiye.aliyun.com #邮箱服务器地址
    username:   #发送邮件账号
    password:  # 发送邮件账号密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false