version : '3'

networks:
  network-redis:
    driver: bridge

x-sentinel-common: &sentinel-common
  image: redis:5.0.5
  networks:
    - network-redis
  deploy:
    resources:
      limits:
        cpus: '0.3'
        memory: 256M
      reservations:
        cpus: '0.1'
        memory: 128M
  command: redis-sentinel /usr/local/etc/redis/sentinel.conf
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"
  healthcheck:
    test: ["CMD", "redis-cli", "-p", "26379", "ping"]
    interval: 30s
    timeout: 3s
    retries: 3

services:
  sentinel1:
    <<: *sentinel-common
    container_name: redis5.0.6-sentinel-1
    ports:
      - '26379:26379'
    volumes:
      - ./sentinel-base.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - SENTINEL_PORT=26379

  sentinel2:
    <<: *sentinel-common
    container_name: redis5.0.6-sentinel-2
    ports:
      - '26380:26379'
    volumes:
      - ./sentinel-base.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - SENTINEL_PORT=26379

  sentinel3:
    <<: *sentinel-common
    container_name: redis5.0.6-sentinel-3
    ports:
      - '26381:26379'
    volumes:
      - ./sentinel-base.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - SENTINEL_PORT=26379