version: '3'

networks:
  network-distributed-lock-mysql:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8.0-distributed-lock
    networks:
      - network-distributed-lock-mysql
    expose:
      - '3306'
    ports:
      - '3310:3306'
    volumes:
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-config/mysql/init:/docker-entrypoint-initdb.d
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--lower_case_table_names=1',
      '--default-time-zone=+8:00',
      '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M
        reservations:
          cpus: '0.4'
          memory: 512M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: "/bin/netstat -anpt|grep 3306"
      interval: 30s
      timeout: 3s
      retries: 1

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed-lock-mysql-app
    networks:
      - network-distributed-lock-mysql
    ports:
      - '9004:9004'
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9004/lock/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3