version : '3'
networks:
  network-docker-spring-boot-test:
    driver: bridge

services:
  web:
    container_name: cn.z201.docker-spring-boot-test
    build:
      context: .
      dockerfile: .
    image: cn.z201.docker-spring-boot-test
    networks:
      - network-docker-spring-boot-test
    expose:
      - '9011'
    ports:
      - '9011:9011'
    depends_on: # 等待其它服务启动完成
      - mysql
      - redis
    links:
      - mysql
      - redis
    healthcheck:
      test: "/bin/netstat -anpt|grep 9000"
      interval: 30s
      timeout: 3s
      retries: 1
  mysql:
    image: mysql:5.7
    container_name: mysql5.7-dev-boot-test
    networks:
      - network-docker-spring-boot-test
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
      - ./docker-config/mysql/init:/docker-entrypoint-initdb.d # 初始化数据库
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--lower_case_table_names=1',
      '--default-time-zone=+8:00']
    environment:
      - MYSQL_ROOT_PASSWORD=root # 设置root密码
    healthcheck:
      test: "/bin/netstat -anpt|grep 3306"
      interval: 30s
      timeout: 3s
      retries: 1
  redis:
    image: redis:5.0.5
    container_name: redis5.0.6-dev-boot-test
    networks:
      - network-docker-spring-boot-test
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - ./docker-config/redis/redis.conf:/etc/redis.conf # 映射数据库配置文件
    command: redis-server /etc/redis.conf # 启动redis命令
    healthcheck:
      test: "/bin/netstat -anpt|grep 6379"
      interval: 30s
      timeout: 3s
      retries: 1
