version: '3'

networks:
  network-distributed-lock-redis:
    driver: bridge

services:
  redis:
    image: redis:8.0
    container_name: redis8.0-distributed-lock
    networks:
      - network-distributed-lock-redis
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - ./docker-config/redis/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    environment:
      - REDIS_PASSWORD=redis_pwd
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M
        reservations:
          cpus: '0.4'
          memory: 512M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["/usr/local/bin/redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3